-- 사역팀 설명 **예시** — tools/ministry-sample-notes.py 가 만든다.
-- ⚠️⚠️ 진짜 부서 자료가 아니다. 화면 확인용 임시 문구이고, 설명 끝에
--       금색 「예시」 표식이 붙어 있다. 진짜 자료가 오면 덮어쓰거나 아래 치우기를 돌린다.
-- ⚠️ 확인된 시간(찬양대·오케스트라)은 건드리지 않는다.

begin;

update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기 (부서 협의)' else schedule_note end, desc_note = '장학 대상을 살피고 지원을 준비합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '장학';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '학기 중 토요일' else schedule_note end, desc_note = '학교와 마을에서 다음세대를 만납니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '교회학교전도';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 11:00' else schedule_note end, desc_note = '발달장애 성도님과 함께 예배드립니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '사랑부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오후 1:30' else schedule_note end, desc_note = '어와나 유아부(3~5세)를 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '퍼글';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오후 1:30' else schedule_note end, desc_note = '어와나 유치부(6~7세)를 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '커비';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오후 1:30' else schedule_note end, desc_note = '어와나 초등부를 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '스팍스/티엔티';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오후 1:30' else schedule_note end, desc_note = '어와나 청소년부를 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '트랙/저니';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 10:40' else schedule_note end, desc_note = '돌 전후 아기와 부모님을 돌봅니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '영아부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 10:40' else schedule_note end, desc_note = '두세 살 아이들과 예배하고 놀이합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '유아부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 10:40' else schedule_note end, desc_note = '유치부 예배와 공과를 함께합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '유치부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 10:40' else schedule_note end, desc_note = '미취학 아이들을 맡아 돌봅니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '새싹부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 9:30' else schedule_note end, desc_note = '초등 저학년 1부 예배와 공과 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '유년부 1부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 11:00' else schedule_note end, desc_note = '초등 저학년 2부 예배와 공과 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '유년부 2부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 9:30' else schedule_note end, desc_note = '초등 고학년 1부 예배와 공과 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '소년부 1부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 11:00' else schedule_note end, desc_note = '초등 고학년 2부 예배와 공과 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '소년부 2부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 11:00' else schedule_note end, desc_note = '중학생 예배와 소그룹을 섬깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '중등부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 11:00' else schedule_note end, desc_note = '고등학생 예배와 소그룹을 섬깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '고등부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '매주 화 오전 10:00' else schedule_note end, desc_note = '어르신 학교를 열고 함께 배웁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교육위원회' and team = '은빛시니어학교';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 9:00~1:00' else schedule_note end, desc_note = '주일 점심 식사를 준비하고 나눕니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교회봉사부' and team = '오병이어 1팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 11:00~2:00' else schedule_note end, desc_note = '주일 점심 식사 후반을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교회봉사부' and team = '오병이어 2팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 8:30~1:00' else schedule_note end, desc_note = '로비 카페에서 음료를 내어 드립니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교회봉사부' and team = '카페운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기 (경조사 발생 시)' else schedule_note end, desc_note = '장례를 당한 가정을 찾아 돕습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교회봉사부' and team = '상례';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '수요일 저녁 7:30' else schedule_note end, desc_note = '수요예배 찬양을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '교회봉사부' and team = '새하늘찬양대';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 1회 (첫째 주)' else schedule_note end, desc_note = '부서 일정을 세우고 살핍니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '문화스포츠부' and team = '운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기' else schedule_note end, desc_note = '공연·전시로 이웃을 만납니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '문화스포츠부' and team = '문화선교';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '행사 준비 기간' else schedule_note end, desc_note = '교회 문화 행사를 준비합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '문화스포츠부' and team = '문화행사';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '매주 목 오전 10:00' else schedule_note end, desc_note = '지역 주민과 함께하는 배움 교실 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '문화스포츠부' and team = '꿈샘문화교실';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '동호회별 상이' else schedule_note end, desc_note = '취미 모임을 꾸리고 이끕니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '문화스포츠부' and team = '동호회';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '토요일 오전' else schedule_note end, desc_note = '체육 모임을 준비하고 함께합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '문화스포츠부' and team = '스포츠';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 예배 시간' else schedule_note end, desc_note = '예배 중 카메라 조정, 자막 송출, 영상 전환(스위처), 음향 운영을 담당합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '방송전산부' and team = '방송실 운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 비정기' else schedule_note end, desc_note = '교회 전산과 앱을 돌봅니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '방송전산부' and team = '전산';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 비정기' else schedule_note end, desc_note = '사진·영상으로 교회 소식을 전합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '방송전산부' and team = '미디어홍보';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 1회' else schedule_note end, desc_note = '교회 소식지를 만듭니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '방송전산부' and team = '새물결';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전' else schedule_note end, desc_note = '새가족부 일정을 세우고 살핍니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '새가족부' and team = '운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 예배 30분 전' else schedule_note end, desc_note = '처음 오신 분을 맞이하고 안내합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '새가족부' and team = '새가족영접';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오후 · 주중 1회' else schedule_note end, desc_note = '새가족이 자리 잡도록 함께 걷습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '새가족부' and team = '새가족정착';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기' else schedule_note end, desc_note = '이단을 분별하고 성도님을 지킵니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '새가족부' and team = '이단대응';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 1회 정기모임' else schedule_note end, desc_note = '국내 선교지를 돕고 오갑니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '선교부' and team = '국내선교';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 1회 정기모임' else schedule_note end, desc_note = '해외 선교사님과 이어집니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '선교부' and team = '세계선교';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오후' else schedule_note end, desc_note = '이웃한 다문화 가정을 섬깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '선교부' and team = '다문화선교';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 예배 시간' else schedule_note end, desc_note = '예배 진행을 준비하고 살핍니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '예배부' and team = '운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 예배 30분 전' else schedule_note end, desc_note = '예배당 입구에서 성도님을 맞이합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '예배부' and team = '영접(웰컴)';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 예배 30분 전' else schedule_note end, desc_note = '출입문에서 인사하고 안내합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '예배부' and team = '출입문영접';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 예배 20분 전' else schedule_note end, desc_note = '본당 자리를 안내합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '예배부' and team = '본당영접';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '분기 1회' else schedule_note end, desc_note = '세례식을 준비하고 돕습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '예배부' and team = '세례예식';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 저녁 7:30' else schedule_note end, desc_note = '단계별 양육 과정을 함께합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '제자양육부' and team = '단계별 제자양육';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '매주 화 오전 10:00' else schedule_note end, desc_note = '어머니들의 말씀 모임을 섬깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '제자양육부' and team = '마더와이즈';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '매주 목 오후 2:00' else schedule_note end, desc_note = '50·60대 인생 후반전을 함께 준비합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '제자양육부' and team = '5060하프타임';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오후 · 주중 1회' else schedule_note end, desc_note = '성경암송 등 신앙운동을 이끕니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '제자양육부' and team = '신앙운동';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기' else schedule_note end, desc_note = '양육 과정 기록과 수료를 관리합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '제자양육부' and team = '학사관리';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 1회' else schedule_note end, desc_note = '전도부 일정을 세우고 살핍니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '전도부' and team = '운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '금요일 오후 2:00' else schedule_note end, desc_note = '마을을 다니며 복음을 전합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '전도부' and team = '행복전도대 - 금요일';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '토요일 오전 10:00' else schedule_note end, desc_note = '마을을 다니며 복음을 전합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '전도부' and team = '행복전도대 - 토요일';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 저녁 (학기제)' else schedule_note end, desc_note = '전도를 배우고 훈련합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '전도부' and team = '전도학교';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '매일 새벽 5:30' else schedule_note end, desc_note = '교회와 성도님을 위해 기도합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '전도부' and team = '중보기도';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 오전 (학기제)' else schedule_note end, desc_note = '기도를 배우고 훈련합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '전도부' and team = '중보기도학교';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '상시 (당번제)' else schedule_note end, desc_note = '기도실을 열고 정돈합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '전도부' and team = '기도실운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 오전 8:00~1:00' else schedule_note end, desc_note = '주차장을 안내하고 정리합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '차량부' and team = '주차안내';
update public.ministry_catalog set desc_note = '주일 1부 예배 찬양을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '할렐루야찬양대';
update public.ministry_catalog set desc_note = '주일 2부 예배 찬양을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '임마누엘찬양대';
update public.ministry_catalog set desc_note = '주일 3부 예배 찬양을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '시온찬양대';
update public.ministry_catalog set desc_note = '청년 예배 찬양을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '실로암찬양대';
update public.ministry_catalog set desc_note = '오후 예배 찬양을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '가브리엘찬양대';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '토요일 오후 리허설' else schedule_note end, desc_note = '주일 2부 예배 경배와 찬양 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '2부 찬양팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '토요일 오후 리허설' else schedule_note end, desc_note = '주일 3부 예배 경배와 찬양 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '3부 찬양팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '토요일 오후 리허설' else schedule_note end, desc_note = '오후 예배 경배와 찬양 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '오후 찬양팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '수요일 오전 리허설' else schedule_note end, desc_note = '수요 오전 예배 찬양 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '수요오전 찬양팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '수요일 오후 리허설' else schedule_note end, desc_note = '수요 오후 예배 찬양 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '수요오후 찬양팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '금요일 저녁 리허설' else schedule_note end, desc_note = '금요 성령집회 찬양 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '금요성령집회 찬양팀';
update public.ministry_catalog set desc_note = '관현악으로 주일 2부 예배를 섬깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '베데스다';
update public.ministry_catalog set desc_note = '관현악으로 주일 3부 예배를 섬깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '비파와수금';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '예배 전 30분' else schedule_note end, desc_note = '예배와 찬양을 위해 기도합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '찬양부' and team = '중보기도팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 (요일 협의)' else schedule_note end, desc_note = '봉사센터 살림을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '희망의복지재단(사회봉사센터)' and team = '봉사센터운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 2회 토요일' else schedule_note end, desc_note = '먹거리를 모아 이웃에 나눕니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '희망의복지재단(사회봉사센터)' and team = '희망푸드뱅크';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 비정기' else schedule_note end, desc_note = '도움이 필요한 가정을 찾아갑니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '희망의복지재단(사회봉사센터)' and team = '사랑의봉사팀';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 오후 (당번제)' else schedule_note end, desc_note = '작은도서관을 열고 지킵니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '희망의복지재단(사회봉사센터)' and team = '도서관책마을';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기' else schedule_note end, desc_note = '홀로 계신 어르신을 돌봅니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '희망의복지재단(사회봉사센터)' and team = '그루터기사역';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 1회' else schedule_note end, desc_note = '목장 사역 전체를 살핍니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = 'L-12(목양부)' and team = '운영';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 비정기' else schedule_note end, desc_note = '목자·목녀를 돕고 필요를 챙깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = 'L-12(목양부)' and team = '목양지원';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 비정기' else schedule_note end, desc_note = '새 가족이 목장에 자리 잡도록 돕습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = 'L-12(목양부)' and team = '정착관리';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '월 1회' else schedule_note end, desc_note = '목장 리더를 세우고 가르칩니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = 'L-12(목양부)' and team = '소그룹 리더교육';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기' else schedule_note end, desc_note = '노회·지역과의 일을 맡습니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '총무부' and team = '대외협력';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '비정기' else schedule_note end, desc_note = '교회 역사와 기록을 정리합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '총무부' and team = '역사홍보';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '경조사 발생 시' else schedule_note end, desc_note = '성도님의 경조사를 챙깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '총무부' and team = '경축부';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주일 · 행사일' else schedule_note end, desc_note = '예배당 안전을 살핍니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '시설부' and team = '안전관리';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 비정기' else schedule_note end, desc_note = '건물과 설비를 고치고 관리합니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '시설부' and team = '시설관리';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '주중 비정기' else schedule_note end, desc_note = '비품과 자재를 챙깁니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '시설부' and team = '자재관리';
update public.ministry_catalog set schedule_note = case when coalesce(schedule_note, '') = '' then '절기·행사 준비 기간' else schedule_note end, desc_note = '절기에 맞춰 예배당을 꾸밉니다 <span style="color:#a08a4a">· 예시</span>' where year = 2027 and committee = '시설부' and team = '데코';

commit;

-- 치우기 — 예시를 전부 지운다(확인된 시간은 남는다)
--   update public.ministry_catalog
--      set desc_note = '', capacity_note = ''
--    where year = 2027 and desc_note like '%예시%';
