-- 필터 값 **예시** — 개발 DB 화면 확인용. 진짜 자료가 아니다.
-- ⚠️ 운영에서 실행하지 말 것. 부서 회신이 오면 그 값으로 덮는다.

update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='장학';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='교회학교전도';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='사랑부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='퍼글';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='커비';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='스팍스/티엔티';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='트랙/저니';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='영아부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='유아부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='유치부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='새싹부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='유년부 1부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='유년부 2부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='소년부 1부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='소년부 2부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='중등부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='고등부';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='10:00', time_to='13:00', freq='매주' where year=2027 and committee='교육위원회' and team='은빛시니어학교';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='12:00', time_to='14:00', freq='격주' where year=2027 and committee='교회봉사부' and team='오병이어 1팀';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='12:00', time_to='14:00', freq='격주' where year=2027 and committee='교회봉사부' and team='오병이어 2팀';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='12:00', time_to='14:00', freq='격주' where year=2027 and committee='교회봉사부' and team='카페운영';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='12:00', time_to='14:00', freq='격주' where year=2027 and committee='교회봉사부' and team='상례';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='07:00', time_to='11:00', freq='매주' where year=2027 and committee='교회봉사부' and team='새하늘찬양대';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='문화스포츠부' and team='운영';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='문화스포츠부' and team='문화선교';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='문화스포츠부' and team='문화행사';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='문화스포츠부' and team='꿈샘문화교실';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='문화스포츠부' and team='동호회';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='문화스포츠부' and team='스포츠';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='방송전산부' and team='방송실 운영';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='방송전산부' and team='전산';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='방송전산부' and team='미디어홍보';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='방송전산부' and team='새물결';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='새가족부' and team='운영';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='새가족부' and team='새가족영접';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='새가족부' and team='새가족정착';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='새가족부' and team='이단대응';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='선교부' and team='국내선교';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='선교부' and team='세계선교';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='선교부' and team='다문화선교';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='예배부' and team='운영';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='예배부' and team='영접(웰컴)';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='예배부' and team='출입문영접';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='예배부' and team='본당영접';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='예배부' and team='세례예식';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='제자양육부' and team='단계별 제자양육';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='제자양육부' and team='마더와이즈';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='제자양육부' and team='5060하프타임';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='제자양육부' and team='신앙운동';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='제자양육부' and team='학사관리';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='전도부' and team='운영';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='20:00', time_to='22:00', freq='매주' where year=2027 and committee='전도부' and team='행복전도대 - 금요일';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=true, time_from='14:00', time_to='17:00', freq='격주' where year=2027 and committee='전도부' and team='행복전도대 - 토요일';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='전도부' and team='전도학교';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='06:00', time_to='07:00', freq='매주' where year=2027 and committee='전도부' and team='중보기도';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='06:00', time_to='07:00', freq='매주' where year=2027 and committee='전도부' and team='중보기도학교';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='전도부' and team='기도실운영';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='08:00', time_to='13:00', freq='격주' where year=2027 and committee='차량부' and team='주차안내';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='07:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='할렐루야찬양대';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='07:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='임마누엘찬양대';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='07:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='시온찬양대';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='07:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='실로암찬양대';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='07:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='가브리엘찬양대';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='08:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='2부 찬양팀';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='08:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='3부 찬양팀';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='08:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='오후 찬양팀';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='10:30', time_to='12:00', freq='매주' where year=2027 and committee='찬양부' and team='수요오전 찬양팀';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='10:30', time_to='12:00', freq='매주' where year=2027 and committee='찬양부' and team='수요오후 찬양팀';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='20:00', time_to='22:00', freq='매주' where year=2027 and committee='찬양부' and team='금요성령집회 찬양팀';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='08:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='베데스다';
update public.ministry_catalog set day_sun=true, day_week=false, day_sat=false, time_from='08:00', time_to='11:00', freq='매주' where year=2027 and committee='찬양부' and team='비파와수금';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='06:00', time_to='07:00', freq='매주' where year=2027 and committee='찬양부' and team='중보기도팀';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='12:00', time_to='14:00', freq='매달' where year=2027 and committee='희망의복지재단(사회봉사센터)' and team='봉사센터운영';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='12:00', time_to='14:00', freq='매달' where year=2027 and committee='희망의복지재단(사회봉사센터)' and team='희망푸드뱅크';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='12:00', time_to='14:00', freq='매달' where year=2027 and committee='희망의복지재단(사회봉사센터)' and team='사랑의봉사팀';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='12:00', time_to='14:00', freq='매달' where year=2027 and committee='희망의복지재단(사회봉사센터)' and team='도서관책마을';
update public.ministry_catalog set day_sun=false, day_week=true, day_sat=false, time_from='12:00', time_to='14:00', freq='매달' where year=2027 and committee='희망의복지재단(사회봉사센터)' and team='그루터기사역';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='L-12(목양부)' and team='운영';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='L-12(목양부)' and team='목양지원';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='L-12(목양부)' and team='정착관리';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='L-12(목양부)' and team='소그룹 리더교육';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='총무부' and team='대외협력';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='총무부' and team='역사홍보';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='총무부' and team='경축부';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='시설부' and team='안전관리';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='시설부' and team='시설관리';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='시설부' and team='자재관리';
update public.ministry_catalog set day_sun=false, day_week=false, day_sat=false, time_from=null, time_to=null, freq=null where year=2027 and committee='시설부' and team='데코';
